/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tw_everest_fdti_FtdiJava */

#ifndef _Included_tw_everest_fdti_FtdiJava
#define _Included_tw_everest_fdti_FtdiJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tw_everest_fdti_FtdiJava
 * Method:    connect
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_tw_everest_fdti_FtdiJava_connect
  (JNIEnv *, jobject);

/*
 * Class:     tw_everest_fdti_FtdiJava
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tw_everest_fdti_FtdiJava_init
  (JNIEnv *, jobject);

/*
 * Class:     tw_everest_fdti_FtdiJava
 * Method:    disConnect
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_tw_everest_fdti_FtdiJava_disConnect
  (JNIEnv *, jobject);

/*
 * Class:     tw_everest_fdti_FtdiJava
 * Method:    nuOfdevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_tw_everest_fdti_FtdiJava_nuOfdevice
  (JNIEnv *, jobject);

/*
 * Class:     tw_everest_fdti_FtdiJava
 * Method:    sendString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tw_everest_fdti_FtdiJava_sendString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tw_everest_fdti_FtdiJava
 * Method:    listen
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tw_everest_fdti_FtdiJava_listen
  (JNIEnv *, jobject);

/*
 * Class:     tw_everest_fdti_FtdiJava
 * Method:    getSysVer
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tw_everest_fdti_FtdiJava_getSysVer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
